name: Test 1Password Access

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v2
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          export-env: false

      - name: Test secret read
        run: |
          op read op://Test/DB_PASS/password
